feat: accessibility on dropdown button
dhis2/ui pull request #1460
Opened 2024-03-07 10:39 UTC by Chisomchima

Accessibility on dropdown button
---

### Description

Implemented [JIRA_ISSUE_ID] https://dhis2.atlassian.net/browse/LIBS-561 by updating the drowpdownButton component to close on click of the escape button. 
---

### Known issues

-   [ ] None

---

### Checklist

-   [ ] API docs are generated
-   [ ] Tests were added
-   [x] Storybook demos were added

_All points above should be relevant for feature PRs. For bugfixes, some points might not be relevant. In that case, just check them anyway to signal the work is done._

---

### Screenshots
- None

---

### Additional Notes 
-None

_supporting text_

2024-04-16 12:05 UTC, Birkbjo commented on components/button/src/dropdown-button/__tests__/dropdown-button.test.js
>          })
Could we have a test that wraps this button in a modal, and make sure that only the dropdown is closed when esc is pressed?

2024-04-25 10:29 UTC, kabaros requested changes
the escape functionality works well, I also tested it with a Modal @Birkbjo 

the question I have is that this fixes one part of [the requirements](https://dhis2.atlassian.net/browse/LIBS-561) - closing with ESC button. But the other part `Similar to changes to Select, a menu opened by a DropdownButton should receive focus when the button is triggered.`

![dropdown-accessibility](https://github.com/dhis2/ui/assets/1014725/f0a2e8d1-1d4e-4519-aeef-120c0a623531)

2024-04-26 12:49 UTC, Chisomchima commented
thanks for the feedback @kabaros and @Birkbjo I have added another test for the escape functionality of the dropdown inside a modal.

2024-04-26 14:54 UTC, Birkbjo commented on components/button/src/dropdown-button/__tests__/dropdown-button.test.js
> +                    expect(queryByText(componentText)).not.toBeInTheDocument()
Could we also verify that the modal is not closed here?
Looks, great!

2024-05-08 17:02 UTC, Chisomchima commented
> @Chisomchima you still haven't handled this requirement from the ticket, right?
> 
> > Similar to changes to Select, a menu opened by a DropdownButton should receive focus when the button is triggered.

I Have written some tests to cover @Birkbjo concerns but I'll have to move this requirement to this jira [ticket](https://dhis2.atlassian.net/browse/LIBS-611)

2024-05-09 09:53 UTC, kabaros commented
Ok - can you please make sure the ticket is in the current sprint, and has the accessibility epic as a parent.

@Birkbjo would you approve the ticket please if you're happy with it.

2024-05-24 11:17 UTC, Birkbjo approved these changes

2024-06-03 10:15 UTC, kabaros approved these changes

2024-06-03 10:15 UTC, merged