fix(headerbar): specify HeaderBar /api/me query fields required
dhis2/ui pull request #464
Opened 2021-01-20 15:58 UTC by mediremi

Closes https://jira.dhis2.org/browse/LIBS-73

2021-01-21 16:39 UTC, HendrikThePendric requested changes
This popped up in my lists of "review requested" list, but I haven't looked at this in great detail yet because there are 53 failing tests. The code is looking good. I did one minor suggestion. I'm happy to look at the failing tests with you tomorrow.

2021-01-21 16:39 UTC, HendrikThePendric commented on packages/widgets/src/HeaderBar/Profile.js
> +                        avatarUrl={avatar ? avatarUrl(avatar, baseUrl) : null}
I think I'd prefer to keep the complexity in the function instead of pulling it out.

2021-01-21 18:40 UTC, mediremi commented
Sorry about the failing tests I didn't realise cypress had network request fixtures. I've updated the URLs of `/api/me` requests in the cypress tests and now all tests pass.

2021-01-22 09:13 UTC, HendrikThePendric approved these changes
Excellent!

2021-01-22 10:42 UTC, merged