fix(header bar): provide size to ImageIcon
dhis2/ui pull request #465
Opened 2021-01-20 16:25 UTC by mediremi

Closes https://jira.dhis2.org/browse/LIBS-101

2021-01-21 16:25 UTC, HendrikThePendric requested changes
This works of course and the code is looking good. But I do wonder if a slightly different approach wouldn't be more suitable:
- The `ImageIcon` doesn't render the wrapper `div` but only the `img` 
- In the `Profile` and `ProfileHeader` component nest the `ImageIcon` in a `Box` with a `width` and `height` specified.

I would prefer that over adding a new prop + dynamic styles to the `ImageIcon`. Lemme know if you agree.

2021-01-21 17:35 UTC, mediremi commented
I agree that sounds much simpler :100:

2021-01-22 10:15 UTC, HendrikThePendric requested changes
Thanks for making these changes. I've left one remark in the code for further improvement. However, I realise there are some more things wrong with the `ImageIcon`:

## Stories and cypress tests
As I note in the code-comment, there are no demo or e2e stories about the image icon functionality. These should be added, and I'd argue that's still within the scope of the current JIRA issue. Usually when we find a bug, we first make an e2e story in which we replicate the bug, and then we fix things using that story. This makes it easier for the reviewer and also it guards against regressions. 

Unfortunately, in this case it seems that we don't have any feature files yet that describe the user-icon functionality, so we will first need to introduce that. Probably in the fixture file we need to cover these scenarios:
- Renders a text icon with the user's initials if no profile-picture is present
- Renders an image icon if a profile picture is present
- The image icon in the headerbar is 36px
- The image icon in the profile menu is 48px
 
So you'll need to create an e2e story for these scenarios (I think you just need 2 stories, not 2). Also I think it'd be good to add one demo that showcases the image icon.

## Style not compliant with design-system
The [design-system specs](https://github.com/dhis2/design-system/blob/master/organisms/header-bar.md) for the `HeaderBar` are very minimal but what we do see is that the image should be circular. So probably that would mean a completely different implementation of the `ImageIcon`, likely a bit more [like this](https://stackoverflow.com/a/25685393/1143502). Technically this is out of scope, so it's up to you if you want to fix it now, or otherwise create a new issue for this. It seems like a fairly small fix to me though.

2021-01-22 10:37 UTC, mediremi commented on packages/widgets/src/HeaderBar/ImageIcon.js
>  )
Ah I didn't realise you could nest styled jsx like that

2021-01-22 12:36 UTC, mediremi commented on packages/widgets/src/HeaderBar/ImageIcon.js
>  )
React doesn't seem to like this:
> img is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

:disappointed:

2021-01-22 17:14 UTC, mediremi commented
Apologies for the great increase in diff size :sweat_smile: 

- While adding the `ImageIcon` demo and the icon E2E stories for the HeaderBar I realised that I needed to refactor to allow passing an avatar URL directly
- It turns out that the icon components are the only ones in the header bar that are not keyboard accessible (they cannot be triggered using the `Enter` key) so I had to wrap them in a `<button>`
- The size of the `TextIcon` was fixed at 36px in both the header bar and profile menu, so I had to make the same changes that I did to `ImageIcon` (namely setting `height` and `width` to `100%`) so that it would grow to 48px in the profile menu

2021-01-25 14:40 UTC, HendrikThePendric requested changes
I've left some more comments in the code, but lso have a general recommendation:
- We should have one `UserIcon` component 
- It should be rendered in a `Box` that sets its dimensions

Currently it seems like we are doing very similar things twice  in the header-bar and the profile-menu.

2021-01-25 14:40 UTC, HendrikThePendric commented on packages/widgets/src/HeaderBar/HeaderBar.js
> +                        }
See first comment. This should not be required

2021-01-25 14:40 UTC, HendrikThePendric commented on packages/widgets/src/HeaderBar/HeaderBar.stories.e2e.js
> +const avatarUrl = `https://placekitten.com/200/300`
IMO using some placeholder image site is fine for this type of thing.

2021-01-25 14:40 UTC, HendrikThePendric commented on packages/widgets/src/HeaderBar/HeaderBar.js
> +    testAvatarUrl: propTypes.string,
remove

2021-01-25 14:40 UTC, HendrikThePendric commented on packages/widgets/src/HeaderBar/ImageIcon.js
> +        <img src={src} alt="user avatar" data-test={dataTestId} />
We use `dataTest`, not `dataTestId` for this type of thing.

2021-01-26 08:42 UTC, amcgee commented
Closes DHIS2-9167

2021-01-27 14:19 UTC, HendrikThePendric approved these changes
Great work, well done.

2021-01-27 14:22 UTC, merged