fix(data-table): use padding instead of fixed cell heights
dhis2/ui pull request #771
Opened 2021-09-30 14:01 UTC by mediremi

Closes https://jira.dhis2.org/browse/LIBS-236

This PR replaces the use of fixed height table cells with a less brittle padding-based approach.

The primary benefit of this change is the elimination of overflow-related issues:

| Before | After |
| --------- | ------ |
| ![image](https://user-images.githubusercontent.com/4295266/135469315-8da12318-7917-46c6-8c15-e06e97f17fb3.png) | ![image](https://user-images.githubusercontent.com/4295266/135469187-fbe2b70f-c2c8-4b35-8af3-7bdb6c70ce61.png) |
| ![image](https://user-images.githubusercontent.com/4295266/135469841-09cbd9f0-c9ce-40a3-a3f7-2daaeb24069e.png)  | ![image](https://user-images.githubusercontent.com/4295266/135469738-4437d61e-df22-4d1c-aacd-f75232447b07.png) |

2021-10-05 10:09 UTC, Mohammer5 reviewed
I'm wondering if the text in the header cells should be top-aligned. Question for @cooper-joe

2021-10-05 11:10 UTC, cooper-joe commented
> I'm wondering if the text in the header cells should be top-aligned.

Yes, I think so. The content (text, optional icons for sorting and filtering) in the header cells should be top-aligned.

2021-10-05 13:05 UTC, HendrikThePendric requested changes
LGTM. But I think two points still need to be addressed:
- [ ] Add a story to demo the text overflow
- [ ] Align top instead of align middle

2021-10-05 15:41 UTC, HendrikThePendric commented
I worked on getting things to align at the top and started to notice another minor issue: the buttons in the sort/filter icon had a visual regression when we moved from height to padding. This turned out to be surprisingly hard to fix without breaking something else. When I discussed the issue with @mediremi we also cam to realise that having full-height buttons gets very weird when having table headers with text that spans multiple lines. @mediremi suggested that probably a square filter button looks just as nice, perhaps nicer, and I think I agree. So this is what I implemented.

@cooper-joe could you have a look at the sort/filter icon-buttons in the current implementation? It's definitely different from the design specs, but I quite like it. We will hold off merging this until we have your seal of approval.

2021-10-05 15:47 UTC, HendrikThePendric commented
@cooper-joe for some reason the PR preview doesn't seem to be updating, I was still looking at the old storybook. If you try the link from the PR preview, please verify you are seeing a story called "Long Cell Content". If not, you are looking at stale code, and I'm afraid you will need to check out the branch and run the storybook yourself.

2021-10-06 08:29 UTC, HendrikThePendric approved these changes
Personally, I am happy with this now.

2021-10-06 09:31 UTC, HendrikThePendric commented on components/table/src/data-table/data-table-column-header/data-table-column-header.styles.js
> +        padding-bottom: 3px;
Good catch. I now have 6px form normal cells and 12px for the large cells. Resulting in heights of 37 and 49px respectively (incl. border). This is the same as on master.

2021-10-06 10:30 UTC, merged