feat(pagination): add support for pagers without a total
dhis2/ui pull request #999
Opened 2022-03-01 14:36 UTC by HendrikThePendric

2022-03-01 15:16 UTC, mediremi approved these changes

2022-03-01 15:23 UTC, amcgee requested changes
Looks like the storybook doesn't correctly hide the total elements for the `no totals` stories.

Approach sounds good and the code looks good from a high level!

2022-03-01 15:23 UTC, amcgee commented on components/pagination/src/page-controls.js
> +            disabled={isLastPage || page === pageCount}
(minor) could this move up to the parent component so we don't need to deal with this branching logic (and additional component) here?  Basically, this component would only have a boolean `isLastPage` prop and the caller would pass `isLastPage={isLastPage || page === pageCount}`

2022-03-01 15:24 UTC, amcgee commented
@HendrikThePendric 
<img width="1204" alt="Screen Shot 2022-03-01 at 16 21 59" src="https://user-images.githubusercontent.com/947888/156196888-94b85858-436d-4ad4-bc28-e9043f42ead7.png">

2022-03-01 15:25 UTC, amcgee commented
>  If the prop is not provided, the component will not crash, but simply use the pageSize and page properties to compute the last item (which could be an incorrect value 🤷‍♂️)

This is probably fine, but maybe we should hide the item numbers if `pageSize` isn't provided...?

2022-03-02 10:27 UTC, HendrikThePendric commented
> > If the prop is not provided, the component will not crash, but simply use the pageSize and page properties to compute the last item (which could be an incorrect value 🤷‍♂️)
> 
> This is probably fine, but maybe we should just always hide the item numbers if `pageSize` isn't provided...?

@amcgee I think you mean `pageLength` here... But I think the point you're making is mainly about not showing a value that may be incorrect, which I think is a very valid point. I was initially concerned about always hiding information which will actually be correct almost all of the time. But it turns out it's perfectly doable to identify the cases where the `lastItem` can't reliably be calculated. So I went back and implemented it as follows:
- If there is a total, the pager will work as it always did
- Without a total it will show information about the page nr, and the item-range.
- In a very specific case, where the last item can't be computed reliably, it will only show information about the current page nr. But this is not something that will happen often, only when all of the conditions below are met: 
    - No `total` provided
    - No `pageLength` provided
    - At last page (i.e. `lastPage` is `true`)
    
In the process I ended up refactoring things quite a bit. I think the different moving parts have more clearly separated responsibilities now.

2022-03-02 13:22 UTC, amcgee approved these changes
Looks good, nice work @HendrikThePendric !

2022-03-02 13:25 UTC, merged